services:

    api_operations:
        class: Ibtikar\ShareEconomyToolsBundle\Service\APIOperations
        arguments: [ '@validator' ]

    firebase:
        class: Ibtikar\ShareEconomyToolsBundle\Service\FireBaseHandler
        arguments: [ '%firebase_url_base%','%firebase_database_secret%' ]

    google.distancematrix:
        class: Ibtikar\ShareEconomyToolsBundle\Service\GoogleDistanceMatrix
        arguments: [ '%google_distance_matrix_url_base%','%google_distance_matrix_key%' ]

    google.directions:
        class: Ibtikar\ShareEconomyToolsBundle\Service\GoogleDirections
        arguments: [ '%google_directions_url_base%','%google_directions_key%' ]

    request.listener.check_api_token:
        class: Ibtikar\ShareEconomyToolsBundle\Listener\CheckAPITokenListener
        arguments: [ '@api_operations', '%android_api_key%', '%ios_api_key%' ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest, priority: 255 }

    request.listener.language:
        class: Ibtikar\ShareEconomyToolsBundle\Listener\LanguageListener
        arguments: [ "%accepted_locales%" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest, priority: 254 }